### ISSUE TITLE
addHeader() lowercase

### ISSUE THREAD

**Issue by dibari** [vlucas/frisby#185]
The addHeader() function (line 235 of frisby.js) takes the passed header names and makes it lowercase.  Is there a reason for this?

I'm explicitly passing a header that uses a capital letter, but it arrives at the server all lowercase.  My API is using a case-specific check for the header, so I'm essentially not able to pass a header.

**Comment by adrianblynch** [comment]
Maybe it's a fall-over from the lowercasing done in expectHeader().

I think the setting of headers for the request should leave casing alone. On the other hand, lowercasing in expectHeader() makes sense because it's the more likely use case.

An option to make case sensitive header checks might be the way forward?

```
expectHeader(key, content, caseSensitive = false)
```

Gotta love a true/false flag :-1:

**Comment by sasikanthnimmagadda** [comment]
I believe, HTTP Headers are expected to be case-insensitive.

FYI.. Below are the references:   
1. http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
2. https://tools.ietf.org/html/rfc7230#section-3.2

Hope this helps..   

~ Sasi

**Comment by vlucas** [comment]
Server specs are case insensitive.
