### ISSUE TITLE
Sync testing/toss.

### ISSUE THREAD

**Issue by dnascimento** [vlucas/frisby#223]
It should support synchronous toss calls. Currently, you need to create a huge chain of callbacks if you want to run a sequence of steps within the same test.

**Comment by ctadeu** [comment]
+1

**Comment by theo01** [comment]
Agreed, synchronous toss calls would make the tests much more readable and plus the --junitreport produce unstructured report files. Since each frisby.create() produce a different file, in case of callbacks chain you end up with one file per callback instead of one file for the whole chain.

This is probably due to the fact that frisby.toss() wrap test execution in a describe() and it().
describe() seems to be executed in parallel whereas it() are sequential.

If we could somehow move the describe() outside of frisby, every toss() call would be sequential and people could decide how to structure their spec suite which define reports files structure.

**Comment by italomaia** [comment]
+1 got into this problem in my first 10 minutes of frisby

**Comment by ganmor** [comment]
I have to say it bite me too. ( Did not even think it was async )

Any test sequence including consecutive tests will be nightmare to write.
Arrow functions might help but....

**Comment by igordeoliveirasa** [comment]
+1

**Comment by imakedon** [comment]
Yes.  Callbacks are uncalled for a and very ugly in this context.

**Comment by dakk** [comment]
Could be useful to have a system like expressjs middlewares where each middleware perform a specific action.
My idea is to achieve something like that:

```
frisby.create ('user session')
   .middleware (signup)
   .middleware (login)
   .middleware (profile)
.toss ()
```

Where "signup" and other middlewares receive an object (where previously called middleware can set session data). Like this:
```
var signup = function (sessiondata, next) {
   return frisby.create (...)...
     .after (err, res, body) {
           sessiondata.username = username;
           sessiondata.password = '123';
           next (sessiondata);
     })
```

**Comment by dakk** [comment]
I wrote a function to help avoiding callback hell: https://gist.github.com/dakk/c701743a6df931210af1571efe5ade35

**Comment by Pablodotnet** [comment]
I got into this problem in my first 10 minutes with Frisby, I'll continue using Newman as long as they fix or work in a method to decide running sequence of our tests.

**Comment by vlucas** [comment]
This is less of an issue in v2 using promise-style `then` chains, but live HTTP calls and these tests were never meant to be run sync. If one test depends on another, they need to be nested.
