### ISSUE TITLE
frisby has no method named 'ttoss'

### ISSUE THREAD

**Issue by freedomfee** [vlucas/frisby#294]
mentioned in your readme.md "To run only one of the tests, replace toss to ttoss" , 
got exception like this.

```
[TypeError: Object #<Frisby> has no method 'ttoss']
```

**Comment by kenmazhao** [comment]
https://github.com/vlucas/frisby/compare/v0.8.5...master

Commits on Jan 23, 2015
 	Sicong He	Fix #65: Add ttoss() to support run single tests.	 fd8909a

Fix #65 is not included 0.8.5

I think you are using  frisby v0.8.5 instead of master, and here is the README.md for 0.8.5:
https://github.com/vlucas/frisby/blob/v0.8.5/README.md

**Comment by arun0009** [comment]
npm install frisby is current using v0.8.5. Looks like there's a bit of difference between master and v0.8.5. @vlucas Can we please have the changes pushed to npm repo? I tried to run ```npm install -g http://github.com/vlucas/frisby/tarball/master``` but that didn't work either

**Comment by JMTyler** [comment]
I'm not concerned with this issue specifically, but agree with @arun0009 that npm is severely outdated.  Is there something that is holding back an npm release or could we please find a way to make one happen?

**Comment by Dashue** [comment]
+1

**Comment by ptim** [comment]
furthermore, https://github.com/vlucas/frisby/blob/master/package.json shows the version as:

```
  "name": "frisby",
  "version": "0.8.4",
```

**Comment by vlucas** [comment]
This will no longer be an issue in v2, as Frisby no longer controls or calls your test describe/it functions.
