### ISSUE TITLE
Is Frisby dead?

### ISSUE THREAD

**Issue by BerndErnst** [vlucas/frisby#347]
Website is outdated, over 100 open Issues, since several months no comment from the dev besides of an announcement of v2 without any timetable.
Is it a good idea to still rely on Frisby?

**Comment by japel** [comment]
latest commit to v2 branch is 3 months ago... its a good question... I'm also relying on it but afraid its gonna die

**Comment by gmarti28** [comment]
I've switched to reqclient
I have more grained control on the request specifics, and better handling
of thenables and promises.
It fits in beautifully  between jasmine and my rest api

hth




*Gaston Martin | gaston.martin@redb.ee <gaston.martin@redb.ee>*


*SDET**T: *+ 54 9 11 5236 7093 <callto:+5491152367093>
*Skype: *gastonmartin77
*F: *4:901/248.77
*A*: Lavalle 348 - 7mo - Buenos Aires - Argentina



2016-10-18 6:39 GMT-03:00 Jan Viktor Apel <notifications@github.com>:

**Comment by vlucas** [comment]
It's not dead - just delayed. I am using the Frisby 2.0 branch in a few upcoming projects of mine. Since 2.0 is in progress, I have stopped addressing issues in the older version - see #316 for an explanation as to why.

I am one of the main organizers of a conference called [ThunderPlains](http://thunderplainsconf.com/), which has proven to be a huge timesink. It's over after early November, so I should be back on track to put out at least a beta build of v2.0 before the year's end.
