### ISSUE TITLE
Frisby v2 - what needs to be done?

### ISSUE THREAD

**Issue by EdwardDrapkin** [vlucas/frisby#361]
Hey there,

We're using Frisby to do some testing, and I had wanted to switch to v2 to take advantage of Promises, but I've noticed that work has stalled.  There's quite an impressive list of tickets, some of which seem to already have fixes, so I'm not sure what's up with it, but I'm willing to spend a few hours a night, a few days a week working on this if you're open to it.

What needs to be done to get v2 shipping and how can I help?

Thanks,
Eddie

**Comment by vlucas** [comment]
Awesome! I just tagged an alpha release so you can play with it: `npm install frisby@2.0.0-alpha.1`.

Right now, it just needs to be used a bit to see where all the cracks are.

**Comment by bkimminich** [comment]
Instead of opening a new help-offering-issue, I'll just put this here:

@vlucas If you are interested in using my pretty extensive API test suite as a guinea pif yourself as I'm slowly migrating it to frisby v2, here you go: https://github.com/bkimminich/juice-shop/tree/frisby2/test/api. That folder is supposed to grow fuller over the next days/weeks while `/api_v0` slowly get emptied.

In case you want to run the migrated tests yourself, you just need to:
```
git clone https://github.com/bkimminich/juice-shop.git
git checkout frisby2
npm install
npm run frisby
```

**Comment by vlucas** [comment]
Closing this because v2.0 has been released.
