### ISSUE TITLE
Support for setup and teardown functions

### ISSUE THREAD

**Issue by nederdirk** [vlucas/frisby#91]
Often it is necessary for testing a REST API to post some test data before running a certain test or spec, is it possible with frisby tests to add setup and teardown functions?

**Comment by mdausmann** [comment]
I really don't understand this at all.  Setup and teardown is fundamental to testing, it's the first thing I tried and it doesn't work.  I had some limited success with using a jasmine spec with a beforeEach and then calling a cleanup in the .after (something like this cluge http://stackoverflow.com/questions/26424639/how-to-intercept-error-when-expect-fails-jasmine-and-frisby) but even that didn't work because all of the beforeEach methods are invoked at once.  Jasmine has excellent support for setup and teardown.  This Library is built on top of Jasmine.  Why can't I use the Jasmine beforeEach/afterEach and just use frisby for the rest goodness??

**Comment by jirizaloudek** [comment]
:+1:

**Comment by mdausmann** [comment]
What I ended up doing....
http://www.michaeldausmann.com/2015/01/integration-testing-restful-endpoint.html

**Comment by igordeoliveirasa** [comment]
+1, I'd like to know how to setup and teardown on Frisby. Thanks.

**Comment by d3ming** [comment]
👍 !  This is a major blocker for adoption for me as well

**Comment by thim81** [comment]
You could resolve this in several alternative ways.
Like create a plain nodejs script that does the setup and teardown functions.
Since these are usually database related actions.

We create per suite a bash script, with in the script the necessary setup and teardown.

Example setup/teardown script:

```
#!/bin/bash

#
# Generic functions
#

function echo_blue () {
  echo -e "\e[94m$1\e[39m"
}

function echo_green () {
  echo -e "\e[92m$1\e[39m"
}

function echo_yellow () {
  echo -e "\e[93m$1\e[39m"
}

function echo_red () {
  echo -e "\e[91m$1\e[39m"
}

function npm_module_install () {
  MODULE_NAME="$1"

  if [ -d "node_modules/$MODULE_NAME" ]; then
    echo_yellow "Module $MODULE_NAME is already installed, skipping..."
  else
    npm install "$MODULE_NAME"  --save-dev
  fi
}

#
# Easy run frisby.js tests script.
#

function install_node_modules () {
  echo_blue "Installing modules for running frisby.js"
  npm_module_install jasmine-node
  npm_module_install frisby
  npm_module_install sleep
}

function create_test_user () {
  echo_blue "Creating test user"
# Do functions to create user
}

function delete_test_user () {
  echo_blue "Delete test user"
# Do functions to delete user
}

function run_tests () {
  echo_blue "Running the tests now..."
  node_modules/jasmine-node/bin/jasmine-node --junitreport --noStack --color spec/
}

#
# Run testing steps
#

# Buildup
install_node_modules
#create_test_user

# Run tests
run_tests

# Teardown
#delete_test_user

```

**Comment by vlucas** [comment]
This is possible in Frisby v2 with Jasmine's built in `beforeEach` and `afterEach` methods.
